name: Netflix API

on:
  push:
    branches: [master]



jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: config.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: INSTALL REQUIREMENTS
        run: pip install -r requirements.txt
      
  deploy:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
        host: 164.92.160.108
        username: root
        key: ${{ secrets.KEY }}
        scripts: |
          git pull
          systemctl restart gunicorn.service

  
    flake8:
    runs-on: ubuntu-latest
    needs: run-tests
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: flake8 Lint
        uses: py-actions/flake8@v2